### PR TITLE
KiCAD and Altium example Gerber files

### PR DESCRIPTION
**Pull request by ajw287**
I've added gerbers output by Altium and KiCAD, both are 2 layer PCBs with some basic components.

### CODE REVIEW

**Comment by Argmaster** [comment]
Could you please determine how they can be licensed / what's the full name of author (company)? As we would like to include them in repository for tests, but pygerber is licensed under MIT which may not be compliant with those resources.

**Comment by Argmaster** [comment]
Also I would like to assure you that resources you have shared previously are actively used for testing on revolution branch.

**Comment by ajw287** [comment]
I am the author of the kiCAD designs - they use library parts and I'm happy for designs to be under MIT,  (though I don't guarantee that the second would work it is an excerpt from a larger design that I haven't tested).  The Altium gerbers are a snippet that a friend sent to me, he has transferred a confirmation that it is okay to distribute it.  Again, it isn't a usable PCB, these are just simple tests of some gerber features.  I think that in the longer run it could be worth collecting some actual open hardware - there must be lots of examples of open hardware projects that have gerbers that are distributed under MIT.  The author of the altium PCB snippet doesn't want  to be referenced, but I can transfer confirmation if you want it by a private message.

**Comment by Argmaster** [comment]
Ok, thanks for the information, I will rely on your word in this case, so we are good to go.
It's completely fine they may not work, as long as it's possible to render them with somewhat compliant Gerber visualizer.
Could you please include screenshot from any reference implementation which can render this code so it will be easy to understand what is expected for each file? Preferably PNG files named same way as GRB files.

Please rebase this branch onto `revolution/2.0.0` branch and move those folders to `test/assets/gerberx3`. Im sorry that I haven't requested this sooner but I'm still in heavy alpha stage there. Parser from main branch is not really capable of supporting macros which is a major drawback for many modern Gerber files, so I must upgrade it.

**Comment by ajw287** [comment]
I've updated my repo to have some renderings of the pcbs - should I create a new pull request?  Also, probably worth installing KiCAD and/or Gerbv as these are becoming standards (KiCAD has a version of Gerbv in it, but I'm unsure of the relationship - I found that I couldn't use the same command line options with kicad/gerbviewer vs gerbv).  I don't know if you want pygerber to cover excellion drill files (I don't know if they are covered in the gerber standards, but they are needed for any PCB with holes in!)?

**Comment by Argmaster** [comment]
> I've updated my repo to have some renderings of the pcbs - should I create a new pull request? Also, probably worth installing KiCAD and/or Gerbv as these are becoming standards (KiCAD has a version of Gerbv in it, but I'm unsure of the relationship - I found that I couldn't use the same command line options with kicad/gerbviewer vs gerbv). I don't know if you want pygerber to cover excellion drill files (I don't know if they are covered in the gerber standards, but they are needed for any PCB with holes in!)?

Sorry for late reply - I have missed this comment and spotted it now while working on including files from those PR.
I have KiCAD installed, but It's not totally obvious for new used to get used to it - I have no background in PCB design, thus everything is new and I am not currently interested in extending my knowledge in this field. 
I think I want pygerber to support excellion drill files, but I can't tell when support for them will show up on roadmap.

**Pull request merged**
